sudo: false
language: elixir
otp_release:
  - 22.0
elixir:
  - 1.9.0
cache:
  directories:
    - /home/travis/.mix/
    - _build
    - deps
script:
  - mix test
  - MIX_ENV=test mix dialyzer --halt-exit-status
